#!/usr/bin/env node

var express = require('express');
var app = express()

const PORT = process.env.PORT || 8080;
const SITE_ROOT = "/site"

app.use(express.static(__dirname + SITE_ROOT))
var options = {
   root: __dirname + SITE_ROOT,
   dotfiles: 'deny',
   headers: {
       'x-timestamp': Date.now(),
       'x-sent': true
   }
 };
app.use((req, res) => res.sendFile(`index.html`, options));
//
// // handle every other route with index.html, which will contain
// // a script tag to your application's JavaScript file(s).
// app.get('*', function (request, response){
//   response.sendFile(path.resolve(__dirname, 'site', 'index.html'))
// })
//
//

console.log(`Listening on ${PORT}...`)
app.listen(PORT)
